# Generated by Django 5.2.6 on 2025-09-17 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('quant_av', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelamento', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Escritorio', 'Escritório'), ('Jantar', 'Jantar'), ('Sala de Estar', 'Sala de Estar'), ('Infantil', 'Infantil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=400)),
                ('address_district', models.CharField(max_length=400)),
                ('address_number', models.CharField(max_length=10)),
                ('address_zip_code', models.CharField(max_length=15)),
                ('address_city', models.CharField(max_length=400)),
                ('address_state', models.CharField(max_length=400)),
                ('address_country', models.CharField(max_length=400)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Cartao', 'Cartão de Crédito')], max_length=20)),
                ('status', models.CharField(choices=[('EM PROCESSAMENTO', 'EM PROCESSAMENTO'), ('PAGAMENTO APROVADO', 'PAGAMENTO APROVADO'), ('NOTA FISCAL EMITIDA', 'NOTA FISCAL EMITIDA'), ('EM PREPARAÇÃO', 'EM PREPARAÇÃO'), ('ENVIADO', 'ENVIADO'), ('RECEBIDO', 'RECEBIDO'), ('PAGAMENTO REPROVADO', 'PAGAMENTO REPROVADO'), ('CANCELADO', 'CANCELADO'), ('SOLICITAÇÃO DE DEVOLUÇÃO', 'SOLICITAÇÃO DE DEVOLUÇÃO'), ('EM DEVOLUÇÃO', 'EM DEVOLUÇÃO'), ('DEVOLVIDO', 'DEVOLVIDO'), ('DEVOLUÇÃO CANCELADA', 'DEVOLUÇÃO CANCELADA')], max_length=50)),
                ('codigo_rastreamento', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrinho')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=4)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='app.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='app.pedido'),
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medidas', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='app.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtos'),
        ),
    ]
