# Generated by Django 5.2.5 on 2025-08-27 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('date_creation', models.DateField()),
                ('date_insertion', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conversion', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('cpf', models.CharField(max_length=12, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=12, unique=True, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('address_street', models.TextField(max_length=400, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=10, verbose_name='numero')),
                ('address_district', models.TextField(verbose_name='bairro')),
                ('address_zip_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('address_city', models.CharField(verbose_name='Cidade')),
                ('address_state', models.CharField(verbose_name='Estado')),
                ('address_country', models.TextField(verbose_name='País')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Foto (URL)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateField(auto_now_add=True)),
                ('date_close', models.DateField(blank=True, null=True)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_FK', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('token_source_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('token_target_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('Account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_account_FK', to='app.account')),
                ('oken_source_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_token_source_FK', to='app.token')),
                ('token_target_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_token_target_FK', to='app.token')),
            ],
        ),
        migrations.CreateModel(
            name='UserGamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loss', models.BooleanField(default=False)),
                ('input_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('output_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('Account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserGamePlay_account_FK', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('Account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserToken_account_FK', to='app.account')),
                ('Token_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserToken_token_FK', to='app.token')),
            ],
        ),
    ]
